import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'od' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.about': 'About',
    'nav.chat': 'Chat',
    
    // Hero Section
    'hero.title': 'Your AI Health Assistant',
    'hero.subtitle': 'Arogya Raksha',
    'hero.description': 'Get instant, reliable health information and guidance 24/7. Ask your health questions and receive expert advice powered by AI.',
    'hero.cta': 'Start Chatting',
    'hero.badge': 'AI Health Assistant',
    
    // Chat
    'chat.title': 'Ask Your Health Questions',
    'chat.subtitle': 'Get Answers for Your Health',
    'chat.description': 'Talk to Arogya Raksha and get instant reliable health information',
    'chat.placeholder': 'Type your health question here...',
    'chat.disclaimer': 'Arogya Raksha only answers health-related questions',
    'chat.greeting': 'Hello! I am Arogya Raksha, your AI health assistant. I only answer health-related questions. What would you like to ask me?',
    'chat.non_health': 'I can only answer health-related questions. Please ask a health-related question.',
    'chat.response1': 'Thank you for your health-related question. Please note that this is general information only. For serious health problems, consult a doctor.',
    'chat.response2': 'Providing health information is my priority. However, for personal medical advice, contact a qualified physician.',
    'chat.response3': 'Your health questions are important. I can provide general guidance, but see a doctor for diagnosis and treatment.',
    
    // Features
    'features.title': 'Why Choose Arogya Raksha?',
    'features.ai.title': 'AI-Powered',
    'features.ai.desc': 'Advanced artificial intelligence trained on medical knowledge',
    'features.multilingual.title': 'Multilingual',
    'features.multilingual.desc': 'Support for multiple Indian languages',
    'features.available.title': '24/7 Available',
    'features.available.desc': 'Get health guidance anytime, anywhere',
    'features.secure.title': 'Secure & Private',
    'features.secure.desc': 'Your health conversations are completely private',
    'features.instant.title': 'Instant Responses',
    'features.instant.desc': 'Get immediate answers to your health questions',
    'features.reliable.title': 'Reliable Information',
    'features.reliable.desc': 'Medically accurate information you can trust',
    
    // About
    'about.title': 'Trusted Health Companion',
    'about.subtitle': 'Reliable Health Partner',
    'about.description': 'Arogya Raksha is India\'s leading AI-based health assistant, specially designed for health-related questions only.',
    'about.users': '10,000+ Users',
    'about.users.desc': 'Thousands of people trust Arogya Raksha daily',
    'about.conversations': '50,000+ Conversations',
    'about.conversations.desc': 'Successful health consultations and information sharing',
    'about.satisfaction': '99% Satisfaction',
    'about.satisfaction.desc': 'User satisfaction rate and positive feedback',
    'about.mission': 'Our Mission',
    'about.mission.desc': 'Making health information accessible to everyone and providing better healthcare through AI technology. We focus only on medical-related questions to give you the best and most relevant information.',
    
    // Footer
    'footer.tagline': 'India\'s leading AI health assistant. 24/7 reliable health information and guidance.',
    'footer.secure': 'Secure',
    'footer.always': '24/7',
    'footer.multilingual': 'Multilingual',
    'footer.services': 'Services',
    'footer.health_consultation': 'Health Consultation',
    'footer.symptom_analysis': 'Symptom Analysis',
    'footer.medicine_info': 'Medicine Information',
    'footer.preventive_care': 'Preventive Care',
    'footer.support': 'Support',
    'footer.usage_guide': 'Usage Guide',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.feedback': 'Feedback',
    'footer.copyright': '© 2024 Arogya Raksha. All rights reserved.',
    'footer.emergency': 'For medical emergencies, contact a doctor immediately.',
  },
  hi: {
    'nav.home': 'होम',
    'nav.features': 'विशेषताएं',
    'nav.about': 'हमारे बारे में',
    'nav.chat': 'चैट',
    'hero.title': 'आपका AI स्वास्थ्य सहायक',
    'hero.subtitle': 'आरोग्य रक्षा',
    'hero.description': '24/7 तत्काल, विश्वसनीय स्वास्थ्य जानकारी और मार्गदर्शन प्राप्त करें। अपने स्वास्थ्य प्रश्न पूछें और AI द्वारा संचालित विशेषज्ञ सलाह प्राप्त करें।',
    'hero.cta': 'चैट शुरू करें',
    'hero.badge': 'AI स्वास्थ्य सहायक',
    'chat.title': 'अपने स्वास्थ्य सवालों के जवाब',
    'chat.subtitle': 'अपने स्वास्थ्य के जवाब पाएं',
    'chat.description': 'आरोग्य रक्षा से बात करें और तुरंत विश्वसनीय स्वास्थ्य जानकारी प्राप्त करें',
    'chat.placeholder': 'अपना स्वास्थ्य प्रश्न यहाँ लिखें...',
    'chat.disclaimer': 'आरोग्य रक्षा केवल स्वास्थ्य संबंधी प्रश्नों का उत्तर देता है',
    'chat.greeting': 'नमस्ते! मैं आरोग्य रक्षा हूं, आपका AI स्वास्थ्य सहायक। मैं केवल स्वास्थ्य संबंधी प्रश्नों का उत्तर देता हूं। आप मुझसे क्या पूछना चाहते हैं?',
    'chat.non_health': 'मैं केवल स्वास्थ्य संबंधी प्रश्नों का उत्तर दे सकता हूं। कृपया कोई स्वास्थ्य संबंधी प्रश्न पूछें।',
    'chat.response1': 'आपके स्वास्थ्य संबंधी प्रश्न के लिए धन्यवाद। कृपया ध्यान दें कि यह केवल सामान्य जानकारी है। गंभीर स्वास्थ्य समस्याओं के लिए डॉक्टर से सलाह लें।',
    'chat.response2': 'स्वास्थ्य संबंधी जानकारी प्रदान करना मेरी प्राथमिकता है। हालांकि, व्यक्तिगत चिकित्सा सलाह के लिए योग्य चिकित्सक से संपर्क करें।',
    'chat.response3': 'आपके स्वास्थ्य प्रश्न महत्वपूर्ण हैं। मैं सामान्य मार्गदर्शन प्रदान कर सकता हूं, लेकिन निदान और उपचार के लिए डॉक्टर से मिलें।',
    'features.title': 'आरोग्य रक्षा क्यों चुनें?',
    'features.ai.title': 'AI-संचालित',
    'features.ai.desc': 'चिकित्सा ज्ञान पर प्रशिक्षित उन्नत कृत्रिम बुद्धिमत्ता',
    'features.multilingual.title': 'बहुभाषी',
    'features.multilingual.desc': 'कई भारतीय भाषाओं का समर्थन',
    'features.available.title': '24/7 उपलब्ध',
    'features.available.desc': 'कभी भी, कहीं भी स्वास्थ्य मार्गदर्शन प्राप्त करें',
    'features.secure.title': 'सुरक्षित और निजी',
    'features.secure.desc': 'आपकी स्वास्थ्य बातचीत पूर्णतः निजी है',
    'features.instant.title': 'तत्काल प्रतिक्रिया',
    'features.instant.desc': 'अपने स्वास्थ्य प्रश्नों के तुरंत उत्तर पाएं',
    'features.reliable.title': 'विश्वसनीय जानकारी',
    'features.reliable.desc': 'चिकित्सकीय रूप से सटीक जानकारी जिस पर आप भरोसा कर सकते हैं',
    'about.title': 'विश्वसनीय स्वास्थ्य साथी',
    'about.subtitle': 'विश्वसनीय स्वास्थ्य साथी',
    'about.description': 'आरोग्य रक्षा भारत का अग्रणी AI-आधारित स्वास्थ्य सहायक है, जो केवल स्वास्थ्य संबंधी प्रश्नों के लिए विशेष रूप से डिज़ाइन किया गया है।',
    'about.users': '10,000+ उपयोगकर्ता',
    'about.users.desc': 'हजारों लोग रोजाना आरोग्य रक्षा पर भरोसा करते हैं',
    'about.conversations': '50,000+ बातचीत',
    'about.conversations.desc': 'सफल स्वास्थ्य परामर्श और जानकारी साझाकरण',
    'about.satisfaction': '99% संतुष्टि',
    'about.satisfaction.desc': 'उपयोगकर्ता संतुष्टि दर और सकारात्मक प्रतिक्रिया',
    'about.mission': 'हमारा मिशन',
    'about.mission.desc': 'स्वास्थ्य जानकारी को सभी के लिए सुलभ बनाना और AI तकनीक के माध्यम से बेहतर स्वास्थ्य सेवा प्रदान करना। हम केवल चिकित्सा-संबंधी प्रश्नों पर केंद्रित रहते हैं ताकि आपको सबसे अच्छी और प्रासंगिक जानकारी मिल सके।',
    'footer.tagline': 'भारत का अग्रणी AI स्वास्थ्य सहायक। 24/7 विश्वसनीय स्वास्थ्य जानकारी और मार्गदर्शन।',
    'footer.secure': 'सुरक्षित',
    'footer.always': '24/7',
    'footer.multilingual': 'बहुभाषी',
    'footer.services': 'सेवाएं',
    'footer.health_consultation': 'स्वास्थ्य परामर्श',
    'footer.symptom_analysis': 'लक्षण विश्लेषण',
    'footer.medicine_info': 'दवा जानकारी',
    'footer.preventive_care': 'निवारक देखभाल',
    'footer.support': 'सहायता',
    'footer.usage_guide': 'उपयोग गाइड',
    'footer.faq': 'FAQ',
    'footer.contact': 'संपर्क करें',
    'footer.feedback': 'फीडबैक',
    'footer.copyright': '© 2024 आरोग्य रक्षा। सभी अधिकार सुरक्षित।',
    'footer.emergency': 'चिकित्सा आपातकाल के लिए तुरंत डॉक्टर से संपर्क करें।',
  },
  od: {
    'nav.home': 'ଘର',
    'nav.features': 'ବିଶେଷତା',
    'nav.about': 'ଆମ ବିଷୟରେ',
    'nav.chat': 'ଚାଟ୍',
    'hero.title': 'ଆପଣଙ୍କର AI ସ୍ୱାସ୍ଥ୍ୟ ସହାୟକ',
    'hero.subtitle': 'ଆରୋଗ୍ୟ ରକ୍ଷା',
    'hero.description': '24/7 ତୁରନ୍ତ, ବିଶ୍ୱସନୀୟ ସ୍ୱାସ୍ଥ୍ୟ ସୂଚନା ଏବଂ ମାର୍ଗଦର୍ଶନ ପ୍ରାପ୍ତ କରନ୍ତୁ। ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ ଏବଂ AI ଦ୍ୱାରା ଚାଳିତ ବିଶେଷଜ୍ଞ ପରାମର୍ଶ ପ୍ରାପ୍ତ କରନ୍ତୁ।',
    'hero.cta': 'ଚାଟ୍ ଆରମ୍ଭ କରନ୍ତୁ',
    'hero.badge': 'AI ସ୍ୱାସ୍ଥ୍ୟ ସହାୟକ',
    'chat.title': 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରଶ୍ନର ଉତ୍ତର',
    'chat.subtitle': 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟର ଉତ୍ତର ପାଆନ୍ତୁ',
    'chat.description': 'ଆରୋଗ୍ୟ ରକ୍ଷା ସହିତ କଥା ହୁଅନ୍ତୁ ଏବଂ ତୁରନ୍ତ ବିଶ୍ୱସନୀୟ ସ୍ୱାସ୍ଥ୍ୟ ସୂଚନା ପ୍ରାପ୍ତ କରନ୍ତୁ',
    'chat.placeholder': 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରଶ୍ନ ଏଠାରେ ଲେଖନ୍ତୁ...',
    'chat.disclaimer': 'ଆରୋଗ୍ୟ ରକ୍ଷା କେବଳ ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବନ୍ଧୀୟ ପ୍ରଶ୍ନର ଉତ୍ତର ଦିଏ',
    'chat.greeting': 'ନମସ୍କାର! ମୁଁ ଆରୋଗ୍ୟ ରକ୍ଷା, ଆପଣଙ୍କର AI ସ୍ୱାସ୍ଥ୍ୟ ସହାୟକ। ମୁଁ କେବଳ ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବନ୍ଧୀୟ ପ୍ରଶ୍ନର ଉତ୍ତର ଦିଏ। ଆପଣ ମୋତେ କଣ ପଚାରିବାକୁ ଚାହୁଁଛନ୍ତି?',
    'chat.non_health': 'ମୁଁ କେବଳ ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବନ୍ଧୀୟ ପ୍ରଶ୍ନର ଉତ୍ତର ଦେଇପାରିବି। ଦୟାକରି ଏକ ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବନ୍ଧୀୟ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ।',
    'chat.response1': 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବନ୍ଧୀୟ ପ୍ରଶ୍ନ ପାଇଁ ଧନ୍ୟବାଦ। ଦୟାକରି ମନେରଖନ୍ତୁ ଯେ ଏହା କେବଳ ସାଧାରଣ ସୂଚନା। ଗମ୍ଭୀର ସ୍ୱାସ୍ଥ୍ୟ ସମସ୍ୟା ପାଇଁ ଡାକ୍ତରଙ୍କ ପରାମର୍ଶ ନିଅନ୍ତୁ।',
    'chat.response2': 'ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବନ୍ଧୀୟ ସୂଚନା ପ୍ରଦାନ କରିବା ମୋର ପ୍ରାଥମିକତା। ତଥାପି, ବ୍ୟକ୍ତିଗତ ଚିକିତ୍ସା ପରାମର୍ଶ ପାଇଁ ଯୋଗ୍ୟ ଚିକିତ୍ସକଙ୍କ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ।',
    'chat.response3': 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରଶ୍ନ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ। ମୁଁ ସାଧାରଣ ମାର୍ଗଦର୍ଶନ ପ୍ରଦାନ କରିପାରିବି, କିନ୍ତୁ ନିଦାନ ଏବଂ ଚିକିତ୍ସା ପାଇଁ ଡାକ୍ତରଙ୍କୁ ଦେଖନ୍ତୁ।',
    'features.title': 'ଆରୋଗ୍ୟ ରକ୍ଷା କାହିଁକି ବାଛନ୍ତୁ?',
    'features.ai.title': 'AI-ଚାଳିତ',
    'features.ai.desc': 'ଚିକିତ୍ସା ଜ୍ଞାନରେ ତାଲିମପ୍ରାପ୍ତ ଉନ୍ନତ କୃତ୍ରିମ ବୁଦ୍ଧିମତ୍ତା',
    'features.multilingual.title': 'ବହୁଭାଷୀ',
    'features.multilingual.desc': 'ଏକାଧିକ ଭାରତୀୟ ଭାଷାର ସମର୍ଥନ',
    'features.available.title': '24/7 ଉପଲବ୍ଧ',
    'features.available.desc': 'ଯେକୌଣସି ସମୟରେ, ଯେକୌଣସି ସ୍ଥାନରେ ସ୍ୱାସ୍ଥ୍ୟ ମାର୍ଗଦର୍ଶନ ପ୍ରାପ୍ତ କରନ୍ତୁ',
    'features.secure.title': 'ସୁରକ୍ଷିତ ଏବଂ ବ୍ୟକ୍ତିଗତ',
    'features.secure.desc': 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ କଥାବାର୍ତ୍ତା ସମ୍ପୂର୍ଣ୍ଣ ବ୍ୟକ୍ତିଗତ',
    'features.instant.title': 'ତୁରନ୍ତ ପ୍ରତିକ୍ରିୟା',
    'features.instant.desc': 'ଆପଣଙ୍କର ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରଶ୍ନର ତୁରନ୍ତ ଉତ୍ତର ପାଆନ୍ତୁ',
    'features.reliable.title': 'ବିଶ୍ୱସନୀୟ ସୂଚନା',
    'features.reliable.desc': 'ଚିକିତ୍ସାଗତ ଭାବରେ ସଠିକ ସୂଚନା ଯାହା ଉପରେ ଆପଣ ବିଶ୍ୱାସ କରିପାରିବେ',
    'about.title': 'ବିଶ୍ୱସନୀୟ ସ୍ୱାସ୍ଥ୍ୟ ସାଥୀ',
    'about.subtitle': 'ବିଶ୍ୱସନୀୟ ସ୍ୱାସ୍ଥ୍ୟ ସାଥୀ',
    'about.description': 'ଆରୋଗ୍ୟ ରକ୍ଷା ହେଉଛି ଭାରତର ଅଗ୍ରଣୀ AI-ଆଧାରିତ ସ୍ୱାସ୍ଥ୍ୟ ସହାୟକ, ଯାହା କେବଳ ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବନ୍ଧୀୟ ପ୍ରଶ୍ନ ପାଇଁ ବିଶେଷ ଭାବରେ ଡିଜାଇନ୍ କରାଯାଇଛି।',
    'about.users': '10,000+ ଉପଭୋକ୍ତା',
    'about.users.desc': 'ହଜାର ହଜାର ଲୋକ ପ୍ରତିଦିନ ଆରୋଗ୍ୟ ରକ୍ଷା ଉପରେ ବିଶ୍ୱାସ କରନ୍ତି',
    'about.conversations': '50,000+ କଥାବାର୍ତ୍ତା',
    'about.conversations.desc': 'ସଫଳ ସ୍ୱାସ୍ଥ୍ୟ ପରାମର୍ଶ ଏବଂ ସୂଚନା ବାଣ୍ଟିବା',
    'about.satisfaction': '99% ସନ୍ତୁଷ୍ଟି',
    'about.satisfaction.desc': 'ଉପଭୋକ୍ତା ସନ୍ତୁଷ୍ଟି ହାର ଏବଂ ସକରାତ୍ମକ ପ୍ରତିକ୍ରିୟା',
    'about.mission': 'ଆମର ମିଶନ୍',
    'about.mission.desc': 'ସ୍ୱାସ୍ଥ୍ୟ ସୂଚନାକୁ ସମସ୍ତଙ୍କ ପାଇଁ ସୁଲଭ କରିବା ଏବଂ AI ପ୍ରଯୁକ୍ତି ମାଧ୍ୟମରେ ଉନ୍ନତ ସ୍ୱାସ୍ଥ୍ୟ ସେବା ପ୍ରଦାନ କରିବା। ଆମେ କେବଳ ଚିକିତ୍ସା-ସମ୍ବନ୍ଧୀୟ ପ୍ରଶ୍ନ ଉପରେ ଧ୍ୟାନ ଦିଅନ୍ତି ଯାହାଫଳରେ ଆପଣଙ୍କୁ ସର୍ବୋତ୍ତମ ଏବଂ ପ୍ରାସଙ୍ଗିକ ସୂଚନା ମିଳିପାରିବ।',
    'footer.tagline': 'ଭାରତର ଅଗ୍ରଣୀ AI ସ୍ୱାସ୍ଥ୍ୟ ସହାୟକ। 24/7 ବିଶ୍ୱସନୀୟ ସ୍ୱାସ୍ଥ୍ୟ ସୂଚନା ଏବଂ ମାର୍ଗଦର୍ଶନ।',
    'footer.secure': 'ସୁରକ୍ଷିତ',
    'footer.always': '24/7',
    'footer.multilingual': 'ବହୁଭାଷୀ',
    'footer.services': 'ସେବା',
    'footer.health_consultation': 'ସ୍ୱାସ୍ଥ୍ୟ ପରାମର୍ଶ',
    'footer.symptom_analysis': 'ଲକ୍ଷଣ ବିଶ୍ଳେଷଣ',
    'footer.medicine_info': 'ଔଷଧ ସୂଚନା',
    'footer.preventive_care': 'ନିବାରଣ ଯତ୍ନ',
    'footer.support': 'ସହାୟତା',
    'footer.usage_guide': 'ବ୍ୟବହାର ଗାଇଡ୍',
    'footer.faq': 'FAQ',
    'footer.contact': 'ଯୋଗାଯୋଗ',
    'footer.feedback': 'ମତାମତ',
    'footer.copyright': '© 2024 ଆରୋଗ୍ୟ ରକ୍ଷା। ସମସ୍ତ ଅଧିକାର ସୁରକ୍ଷିତ।',
    'footer.emergency': 'ଚିକିତ୍ସା ଜରୁରୀ ପରିସ୍ଥିତି ପାଇଁ ତୁରନ୍ତ ଡାକ୍ତରଙ୍କ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ।',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.features': 'বৈশিষ্ট্য',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.chat': 'চ্যাট',
    'hero.title': 'আপনার AI স্বাস্থ্য সহায়ক',
    'hero.subtitle': 'আরোগ্য রক্ষা',
    'hero.description': '24/7 তাৎক্ষণিক, নির্ভরযোগ্য স্বাস্থ্য তথ্য এবং নির্দেশনা পান। আপনার স্বাস্থ্য প্রশ্ন জিজ্ঞাসা করুন এবং AI দ্বারা চালিত বিশেষজ্ঞ পরামর্শ পান।',
    'hero.cta': 'চ্যাট শুরু করুন',
    'hero.badge': 'AI স্বাস্থ্য সহায়ক',
    'chat.title': 'আপনার স্বাস্থ্য প্রশ্নের উত্তর',
    'chat.subtitle': 'আপনার স্বাস্থ্যের উত্তর পান',
    'chat.description': 'আরোগ্য রক্ষার সাথে কথা বলুন এবং তাৎক্ষণিক নির্ভরযোগ্য স্বাস্থ্য তথ্য পান',
    'chat.placeholder': 'আপনার স্বাস্থ্য প্রশ্ন এখানে লিখুন...',
    'chat.disclaimer': 'আরোগ্য রক্ষা শুধুমাত্র স্বাস্থ্য সম্পর্কিত প্রশ্নের উত্তর দেয়',
    'chat.greeting': 'নমস্কার! আমি আরোগ্য রক্ষা, আপনার AI স্বাস্থ্য সহায়ক। আমি শুধুমাত্র স্বাস্থ্য সম্পর্কিত প্রশ্নের উত্তর দিই। আপনি আমাকে কি জিজ্ঞাসা করতে চান?',
    'chat.non_health': 'আমি শুধুমাত্র স্বাস্থ্য সম্পর্কিত প্রশ্নের উত্তর দিতে পারি। দয়া করে একটি স্বাস্থ্য সম্পর্কিত প্রশ্ন জিজ্ঞাসা করুন।',
    'chat.response1': 'আপনার স্বাস্থ্য সম্পর্কিত প্রশ্নের জন্য ধন্যবাদ। দয়া করে মনে রাখবেন যে এটি শুধুমাত্র সাধারণ তথ্য। গুরুতর স্বাস্থ্য সমস্যার জন্য ডাক্তারের পরামর্শ নিন।',
    'chat.response2': 'স্বাস্থ্য সম্পর্কিত তথ্য প্রদান করা আমার অগ্রাধিকার। তবে, ব্যক্তিগত চিকিৎসা পরামর্শের জন্য যোগ্য চিকিৎসকের সাথে যোগাযোগ করুন।',
    'chat.response3': 'আপনার স্বাস্থ্য প্রশ্ন গুরুত্বপূর্ণ। আমি সাধারণ নির্দেশনা প্রদান করতে পারি, কিন্তু নির্ণয় এবং চিকিৎসার জন্য ডাক্তার দেখুন।',
    'features.title': 'কেন আরোগ্য রক্ষা বেছে নেবেন?',
    'features.ai.title': 'AI-চালিত',
    'features.ai.desc': 'চিকিৎসা জ্ঞানে প্রশিক্ষিত উন্নত কৃত্রিম বুদ্ধিমত্তা',
    'features.multilingual.title': 'বহুভাষিক',
    'features.multilingual.desc': 'একাধিক ভারতীয় ভাষার সমর্থন',
    'features.available.title': '24/7 উপলব্ধ',
    'features.available.desc': 'যেকোনো সময়, যেকোনো জায়গায় স্বাস্থ্য নির্দেশনা পান',
    'features.secure.title': 'নিরাপদ এবং ব্যক্তিগত',
    'features.secure.desc': 'আপনার স্বাস্থ্য কথোপকথন সম্পূর্ণ ব্যক্তিগত',
    'features.instant.title': 'তাৎক্ষণিক প্রতিক্রিয়া',
    'features.instant.desc': 'আপনার স্বাস্থ্য প্রশ্নের তাৎক্ষণিক উত্তর পান',
    'features.reliable.title': 'নির্ভরযোগ্য তথ্য',
    'features.reliable.desc': 'চিকিৎসাগতভাবে সঠিক তথ্য যার উপর আপনি নির্ভর করতে পারেন',
    'about.title': 'বিশ্বস্ত স্বাস্থ্য সঙ্গী',
    'about.subtitle': 'নির্ভরযোগ্য স্বাস্থ্য অংশীদার',
    'about.description': 'আরোগ্য রক্ষা ভারতের অগ্রণী AI-ভিত্তিক স্বাস্থ্য সহায়ক, যা বিশেষভাবে শুধুমাত্র স্বাস্থ্য সম্পর্কিত প্রশ্নের জন্য ডিজাইন করা হয়েছে।',
    'about.users': '10,000+ ব্যবহারকারী',
    'about.users.desc': 'হাজার হাজার মানুষ প্রতিদিন আরোগ্য রক্ষায় আস্থা রাখেন',
    'about.conversations': '50,000+ কথোপকথন',
    'about.conversations.desc': 'সফল স্বাস্থ্য পরামর্শ এবং তথ্য ভাগাভাগি',
    'about.satisfaction': '99% সন্তুষ্টি',
    'about.satisfaction.desc': 'ব্যবহারকারী সন্তুষ্টি হার এবং ইতিবাচক প্রতিক্রিয়া',
    'about.mission': 'আমাদের মিশন',
    'about.mission.desc': 'স্বাস্থ্য তথ্য সবার জন্য সহজলভ্য করা এবং AI প্রযুক্তির মাধ্যমে উন্নত স্বাস্থ্যসেবা প্রদান করা। আমরা শুধুমাত্র চিকিৎসা-সম্পর্কিত প্রশ্নে মনোনিবেশ করি যাতে আপনি সর্বোত্তম এবং প্রাসঙ্গিক তথ্য পেতে পারেন।',
    'footer.tagline': 'ভারতের অগ্রণী AI স্বাস্থ্য সহায়ক। 24/7 নির্ভরযোগ্য স্বাস্থ্য তথ্য এবং নির্দেশনা।',
    'footer.secure': 'নিরাপদ',
    'footer.always': '24/7',
    'footer.multilingual': 'বহুভাষিক',
    'footer.services': 'সেবা',
    'footer.health_consultation': 'স্বাস্থ্য পরামর্শ',
    'footer.symptom_analysis': 'লক্ষণ বিশ্লেষণ',
    'footer.medicine_info': 'ওষুধের তথ্য',
    'footer.preventive_care': 'প্রতিরোধমূলক যত্ন',
    'footer.support': 'সহায়তা',
    'footer.usage_guide': 'ব্যবহার গাইড',
    'footer.faq': 'FAQ',
    'footer.contact': 'যোগাযোগ',
    'footer.feedback': 'মতামত',
    'footer.copyright': '© 2024 আরোগ্য রক্ষা। সমস্ত অধিকার সংরক্ষিত।',
    'footer.emergency': 'চিকিৎসা জরুরি অবস্থার জন্য অবিলম্বে ডাক্তারের সাথে যোগাযোগ করুন।',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}