// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkwhonjnfuvhlxogldum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrd2hvbmpuZnV2aGx4b2dsZHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTY2MzAsImV4cCI6MjA3NDAzMjYzMH0.LUYwPiwUHRPB-kGEfeOvsyoIUBJvqfl6tYlOk2bZY-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});